### ISSUE TITLE
[Power Platform communication site template] File not found errors

### ISSUE THREAD

**Issue by Craig-Humphrey** [microsoft/coe-starter-kit#4115]
### Describe your bug, question or feature ask.

Just installed the Power Platform Hub (aka communication site template) for the first time.
Package downloaded on 4th November 2022.

While the Deploy script seems to run and complete successfully, the console is full of file not found exceptions, though I can't see what file they relate to.

Is this a problem, or is it a normal error as the script perhaps checks for the existence of a file, before uploading/creating it?

Thanks
Craig

  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
ServerErrorCode: -2147024894
ServerErrorTypeName: System.IO.FileNotFoundException
ServerErrorTraceCorrelationId: 251275a0-c0e9-1000-caad-280391b0b7d5
ServerErrorValue:
ServerErrorDetails:

**Comment by Laskewitz** [comment]
Hi @Craig-Humphrey, 

Those file not found exceptions are because of the logging we have turned on. Nothing to worry about. When the template uploads all the files, it checks if it exists. That way - the script knows if the files should be created (if it is not found) or updated (when it is found). Because the files don't exist yet, you get the errors which you are seeing.

So long story short: nothing is wrong. 👍🏼 

Hope you enjoy the template!

Kind regards,
Daniel
