### ISSUE TITLE
[CoE Starter Kit - QUESTION] Wizard app rarities after uninstalling and reinstalling core components solution

### ISSUE THREAD

**Issue by HenningStrand** [microsoft/coe-starter-kit#5752]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

Noticed something strange when running setup wizard after having reinstalled the 4.4.2 version of the core solution. Some controls don't work properly, like the left stage marker is not showing and the setting of the ProductionEnvironment variable to no does not work + getting 'Error loading control' at top of screen for some stages (this goes away after short time, when the back/next buttons become active).
![image](https://github.com/microsoft/coe-starter-kit/assets/72507624/49628da9-d953-4664-9655-a8c5e83467f1)

Since I was getting the 'Error loading control' I was looking at the wizard flows. All the required ones are turned on. BUT, strangely enough for two of them I see that they have runs logged one week ago, after the initial install, even if the solution was removed and then reinstalled a week later...

GetUserDetails and GetCurrentEnvironment show as being created one week ago..
![image](https://github.com/microsoft/coe-starter-kit/assets/72507624/cc1240fd-928b-4507-8bc3-16b6cb31ae30)
![image](https://github.com/microsoft/coe-starter-kit/assets/72507624/ef58ee9a-9007-4380-8d47-42f22c9aa610)

I tried the same back in out test tenant, deleting and reinstalling the core solution, and get exactly the same behavior there. 

Seems like removing and reinstalling the core components solution is not a good idea! You seen the same?

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.4.2

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello. Yes deleting a solution does not actually delete all things from it from the environment. 

I typically advice if you are reusing an environment for testing, you need to use backup/restore (making sure you come out of administrative mode after restore). Even that is not exactly the same as a clean env but its closer. 

We also just did a big pass on papercut issues in the Setup Wizard in the June release. Please see https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-June2023

**Comment by HenningStrand** [comment]
I just did a clean install in a new environment and see the same behavior. I am suspecting some roll out of new update on the Power Platform might have some impact... Testing some more

**Comment by Jenefer-Monroe** [comment]
A clean install of the new June release?

**Comment by HenningStrand** [comment]
No. The same April one that I have been working with some time. Seems that something has changed in the the Wizard worked differently just a short while ago.

**Comment by Jenefer-Monroe** [comment]
Got it. OK yes I did a big pass on the Setup Wizard for the June release so I'm not sure about the behavior for April at this point.

**Comment by HenningStrand** [comment]
When clicking the link of 'error loading control' I get this. 
![image](https://github.com/microsoft/coe-starter-kit/assets/72507624/44e9bb32-0f21-4605-a951-da7f93531887)

the errorDetails gives this:

Error Details: TypeError: Cannot read properties of null (reading 'toLowerCase')
    at l.updateView (wrapped.https://pafeblobprodam.blob.core.windows.net/20230608t000000z9d70dc56ab464a2b8684f7ddc6127e06/a42995c1-0215-405d-bbe7-290a7ad786b6/web/admin_initialsetuppage_d45cf/web/PCFControls/cat_PowerCAT.Spinner/PowerCAT.Spinner.bundle.js;:16:1557)
    at eval (wrapped.https://content.powerapps.com/resource/app/fqf2idneg8aa4/ctrllib/PCFControls/js/PCFControlWrapper.js;:16:1518128)
    at t._measureLifecycleMethod (wrapped.https://content.powerapps.com/resource/app/fqf2idneg8aa4/ctrllib/PCFControls/js/PCFControlWrapper.js;:16:1494382)
    at t._renderMainControlComponent (wrapped.https://content.powerapps.com/resource/app/fqf2idneg8aa4/ctrllib/PCFControls/js/PCFControlWrapper.js;:16:1518068)
    at t.renderWrappedMainElement (wrapped.https://content.powerapps.com/resource/app/fqf2idneg8aa4/ctrllib/PCFControls/js/PCFControlWrapper.js;:16:1520799)
    at t._renderInternal (wrapped.https://content.powerapps.com/resource/app/fqf2idneg8aa4/ctrllib/PCFControls/js/PCFControlWrapper.js;:16:1524612)
    at t.render (wrapped.https://content.powerapps.com/resource/app/fqf2idneg8aa4/ctrllib/PCFControls/js/PCFControlWrapper.js;:16:1525742)
    at ce (https://content.powerapps.com/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:299:136)
    at qg (https://content.powerapps.com/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:298:440)
    at hi (https://content.powerapps.com/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:305:285)

Activity Id: 2a512660-01f2-4d90-b4ea-7d805aa2b402

**Comment by Jenefer-Monroe** [comment]
Thats an issue with the creator kit control. What version of the creator kit do you have installed?

![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/be7bf361-727f-4ee4-b4f4-f35c8487e522)

**Comment by SPMush** [comment]
Experienced the same error with the Spinner control during the setup Wizard 
I have Creator Kit 1.0.20230421.1 (April 23) installed.

**Comment by Jenefer-Monroe** [comment]
Great thank you, moving to creator kit team. 
Team, this control still works in older version of the same screen, so a regression in the control itself.
