### ISSUE TITLE
[CoE Starter Kit - QUESTION] What version of the starter kit and the creator kit should we use to do a fresh install at this time?

### ISSUE THREAD

**Issue by pnoot7** [microsoft/coe-starter-kit#5865]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

With the current issues on the June release (Set up wizard gives "Custom Control with Id: PowerCAT.Spinner failed to render; Message: Cannot read properties of null (reading 'toLowerCase')"), I see the pinned issue related to this, and seems its related to the creator kit. I have CoE core 4.9 (June) and Creator kit 1.0.20230421.1, but cannot proceed through the setup wizard in fresh environment.

I was working to do a fresh install after the failed upgrade to the May release I had, but am again stuck unable to complete the setup wizard.

Is there a known good configuration that we should be using to install/setup? Will a hotfix release be happening?

Alternatively, I post more details to see if we can fix the versions I have.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2023

### What app or flow are you having the issue with?

CoE Setup and Upgrade Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by manuelap-msft** [comment]
Hello,

unfortunately we're currently impacted by a product bug that causes the issue you're seeing in PCF components used in custom pages, see https://github.com/microsoft/coe-starter-kit/issues/5815#issuecomment-1590661034 for more details. 

As this is a product bug, there's nothing you (or we) can do - we are working with the Power Apps Engineering team, and they've identified the root cause and a potential fix is in work but we'll have to wait until that rolls out.

Thank you for understanding, we'll keep this thread updated once we learn more on timelines.
Manuela

**Comment by LizethRegules** [comment]
@manuelap-msft @Jenefer-Monroe, is it weird that I have June 2023 version and the spinner is loading for me? Installing for a client, we see the error on their side and the spinner not loading, plus the blue checkmarks aren't appearing either, but for me, it is working perfectly fine.
<img width="800" alt="image" src="https://github.com/microsoft/coe-starter-kit/assets/100951593/28880890-c273-47cf-aa9e-d1c1145700e7">

**Comment by Jenefer-Monroe** [comment]
I dont know the exact mechanism to guess if or where you will be impacted but I do know that this issue (all blue checks) is a symptom. And you may in a single envt see some things repro (all blue checks) but not others (spinner fails to load)

Sorry we cant be of more assistance. We are pressing for a fix and also hardening our apps to not be vulnerale to this issue in the future.

**Comment by Jenefer-Monroe** [comment]
This was due to a product but which has since been hotfixed.
In order to get their hotfix into your app, here is what you need to do. For any app where you are seeing these types of issues, you will need to republish the MDA for it. I have validated that this does not create an unmanaged layer so you will be good going forward as well.
1. Go to your CoE Environment > Apps
2. Edit the Model Driven App where you see this
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8a9d8808-b0e2-4da4-bfac-82601837c5f5)
3. Once in the MDA hit Publish and wait till publish completes
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2de49f4d-786d-4c3c-9920-7ab70c5c78b9)
4. Now reopen the Model Driven App and the issue should be resolved.

**Comment by pnoot7** [comment]
Hello. I created a completely new environment. Set the DLP policies, imported the creator kit (enabled the framework). Imported the core components, and now I get this error:

![image](https://github.com/microsoft/coe-starter-kit/assets/125403575/4959c730-779a-40e2-a41e-cc8b25b43317)

Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bkind%2C%20severity%2C%20errorHttpResponse%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Error code: 0x0
Session Id: 67dc9065-1257-4d2c-b989-feaf0fefdcf1
Activity Id: e7df508d-4538-4499-a812-76e514341cdb
Time: Fri Jun 23 2023 09:33:41 GMT-0400 (Eastern Daylight Time)

Download Log File

Logfile:
Error Details: Invariant Violation: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bkind%2C%20severity%2C%20errorHttpResponse%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at pb (https://gov.content.powerapps.us/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:213:454)
    at n (https://gov.content.powerapps.us/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:214:221)
    at Ac (https://gov.content.powerapps.us/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:271:369)
    at https://gov.content.powerapps.us/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:281:190
    at N (https://gov.content.powerapps.us/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:291:3)
    at hi (https://gov.content.powerapps.us/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:307:194)
    at Qg (https://gov.content.powerapps.us/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:345:293)
    at Rg (https://gov.content.powerapps.us/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:346:168)
    at Sc (https://gov.content.powerapps.us/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:359:109)
    at Z (https://gov.content.powerapps.us/resource/app/65dekugibpne1/publish/js/pa.oss.bundle2.js:357:492)

Activity Id: e7df508d-4538-4499-a812-76e514341cdb

Should I open a new issue?

**Comment by Jenefer-Monroe** [comment]
This is due to a product bug which has since been hotfixed.
In order to get their hotfix into your app, here is what you need to do. For any app where you are seeing these types of issues, you will need to republish the MDA for it. I have validated that this does not create an unmanaged layer so you will be good going forward as well.
1. Go to your CoE Environment > Apps
2. Edit the Model Driven App where you see this
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/8a9d8808-b0e2-4da4-bfac-82601837c5f5)
3. Once in the MDA hit Publish and wait till publish completes
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/2de49f4d-786d-4c3c-9920-7ab70c5c78b9)
4. Now reopen the Model Driven App and the issue should be resolved.

**Comment by pnoot7** [comment]
So I need to do this even with a completely fresh environment and solution import ( I did it like an hour before posting that new error)

This is a different error now.

**Comment by pnoot7** [comment]
If I go to edit the set up wizard MDA, I get more errors:
![image](https://github.com/microsoft/coe-starter-kit/assets/125403575/836f0653-2a13-4bab-9f6d-995154a404f9)

Something went wrong
Learn more
Hide details
Error Code: runtimeCanvasAppError
Session Id: 55fa12e2-8f49-478d-be07-659de357d37f
Activity Id: 6baaa369-1b1c-45b7-a79c-fff0c10cf5b1
Timestamp: Fri Jun 23 2023 10:14:53 GMT-0400 (Eastern Daylight Time)
Error loading script
UciError: Error loading script at s (https://org7e1bf7a3.crm9.dynamics.com/uclient/scripts/app.js?v=1.4.5821-2305.2:33:924363) at https://org7e1bf7a3.crm9.dynamics.com/uclient/scripts/custompage.js?v=1.4.5821-2305.2:4:87316

**Comment by Jenefer-Monroe** [comment]
These errors are all the same cause having to do with default enums values not getting filled. It surfaces in a million ways depending on the control. 

Please post in this issue: https://github.com/microsoft/powercat-creator-kit/issues/338
It is where the product dev is walking for updates.

**Comment by Jenefer-Monroe** [comment]
@pnoot7 we have also hardened the apps against this default enum issue and so the July release will not rely on any default translations. Worst case scenario you could wit for that release.

**Comment by pnoot7** [comment]
I've been down since the may release, so the earlier the better. My management isn't happy with the tool/support at this point and I don't know what else to do.

**Comment by Jenefer-Monroe** [comment]
When you say you are "down" what does that mean? 
You shoudl be able to upgrade without the setup wizard, you can just follow the instructions here: https://learn.microsoft.com/power-platform/guidance/coe/setup-core-components
Its lame but you should be able to gather inventory.

**Comment by pnoot7** [comment]
May update broke my existing environment. After talking to support, decided to start fresh (old environment was not built by me and was not built to suggested standards), now cannot get an install/setup to complete.

**Comment by Jenefer-Monroe** [comment]
oh I see. Yes you should be able to manually install using those instructions then. Sorry for the inconveniance on the setup tool.
