### ISSUE TITLE
[CoE Starter Kit - BUG] Dataflow: CoE BYODL Makers

### ISSUE THREAD

**Issue by Titoleto** [microsoft/coe-starter-kit#6486]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We have updated the CoE Starter Kit this Monday and today checking the Dataflows execution we have verified that yesterday the refresh has failed. Looking at the whole refresh history, I could see that this same error also occurred a week ago, the problem is that today, no matter how hard I try to do the manual refresh, I still get the error I report.

EDIT (2023/08/31): After 4 manual refreshes, the error no longer occurred, so I understand that it may be a one-off error.
EDIT (2023/09/01): This morning when we checked the Dataflows, we found that it failed again. Same as yesterday, by clicking on refresh manually it has already been executed correctly.

The error that appears in the history is as follows
![image](https://github.com/microsoft/coe-starter-kit/assets/107242690/1fff0d94-610e-4ef4-80e7-afe8d173fcaa)

When we edit the Dataflow this is the error that appears when trying to load the Makers table (below the error).
![image](https://github.com/microsoft/coe-starter-kit/assets/107242690/8bfcfb1a-f36d-440b-8965-5e190a88cdf3)

`DataSource.Error: OData: Request failed: The remote server returned an error: (400) Bad Request. (System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Dynamics.CDS.AADPlugins.GraphApiClient.<>c__DisplayClass25_2.<<ExecuteGraphApiRequest>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Dynamics.CDS.AADPlugins.GraphApiClient.ExecuteGraphApiRequest(IPluginExecutionContext pluginContext, String columnsToRetrieve, String filterCondition, String orderBy, String searchQuery, Int32 topCount, String& nextLink, String pagingCookie)
   at Microsoft.Dynamics.CDS.AADPlugins.PersonTypeRetrieveMultiplePlugin.RetrieveMultiple(IPluginExecutionContext pluginContext, EntityMetadata entityMetadata, IGraphApiClient graphApiClient)
   at Microsoft.Dynamics.CDS.AADPlugins.PersonTypeRetrieveMultiplePlugin.<>c__DisplayClass2_0.<ExecuteInternal>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.CDSRuntime.SandboxWorker.SandboxFirstPartyPluginLogger.Execute(String activityName, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Dynamics.CDS.AADPlugins.PersonTypeRetrieveMultiplePlugin.ExecuteInternal(IPluginExecutionContext pluginContext, IOrganizationService organizationService, EntityMetadata entityMetadata, IGraphApiClient graphApiClient)
   at Microsoft.Dynamics.CDS.AADPlugins.PluginBase.<>c__DisplayClass9_0.<Execute>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.CDSRuntime.SandboxWorker.SandboxFirstPartyPluginLogger.Execute(String activityName, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Dynamics.CDS.AADPlugins.PluginBase.Execute(IServiceProvider serviceProvider)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Dynamics.CDS.AADPlugins.GraphApiClient.<>c__DisplayClass25_2.<<ExecuteGraphApiRequest>b__1>d.MoveNext()
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
<---
)
`

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.13

### What app or flow are you having the issue with?

CoE BYODL Makers Dataflow

### What method are you using to get inventory and telemetry?

Data Export

**Comment by Jenefer-Monroe** [comment]
Hello we have seen a few people hit similar issues and it appears to be a product limitation. 
This is being driven via this bug: https://github.com/microsoft/coe-starter-kit/issues/6153
So I'll go aheand and dupe you to that and you can iterate with the folks there to see if you can get a fix from the product team for it.
